name: FTP Sync

on:
  # L'action est lancée chaque matin à 7h00
  schedule:
    - cron: '0 7 * * *'
  # L'action peut également être lancée manuellement à tout moment
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Installer l'outil cURL
      run: sudo apt-get install curl

    - name: Récupérer le fichier sur le FTP
      # Récupérer les secrets stockés dans github
      # pour les utiliser comme identifiants de connexion FTP
      env:
        FTP_LOGIN: ${{ secrets.FTP_LOGIN }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      # Utiliser l'outil cURL pour récupérer le fichier
      # en spécifiant l'URL ftp et les identifiants de connexion
      # à partir des secrets stockés
      run: curl ftp://${{ env.FTP_LOGIN }}:${{ env.FTP_PASSWORD }}@ftp.ymzk1123.odns.fr/file.txt -o file.txt
    - name: Stocker le fichier en local
      # Utiliser l'action "upload-artifact" pour stocker le fichier
      # en local dans le dépôt github
      uses: actions/upload-artifact@v1
      with:
        name: file
        path: file.txt
